spring:
  application:
    name: alex-spring-boot-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_jpa
    username: postgres
    password: 8500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  # CONFIG FOR H2 in memory database

  #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #    username: sa
  #    password:
  #    driverClassName: org.h2.Driver
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #      settings:
  #        web-allow-others: true
  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    defer-datasource-initialization: true
  main:
    banner-mode: console
task:
  scheduling:
    pool:
      size: 5
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1
logging:
  level:
    root: INFO
    sql: WARN
    org:
      springframework:
        web: OFF

stripe:
  api-key: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6-demo
  url: https://api.stripe.com-demo
